### PR TITLE
Add @Nullable and @NotNull for public methodes of JSONAPIDocument

### PR DESCRIPTION
**Pull request by Kevinrob**
This help the IDE to avoiding `NullPointerException`.  
Koltin can infer correct type too.

Doc for Kotlin: https://kotlinlang.org/docs/reference/java-interop.html#nullability-annotations

### CODE REVIEW

**Comment by Kevinrob** [comment]
Hi @jasminb ! Can you check my little PR please? 😀

**Comment by jasminb** [comment]
Hey @Kevinrob,

Sorry for tardiness, will take a look during the weekend and merge.

Cheers

**Comment by jasminb** [comment]
Please update the target branch to `develop`, there is a newer version of added dependency on mvn-central, should we use that one instead?

**Comment by Kevinrob** [comment]
@jasminb I changed the target branch to `develop` 👍

**Comment by jasminb** [comment]
Merged, thanks @Kevinrob!

**Pull request merged**
