### PR TITLE
Fix for #165 @RelationshipLinks also serialized to attributes + using…

### PR DESCRIPTION
**Pull request by marceloverdijk**
… namingStrategy for other fields being removed

### CODE REVIEW

**Comment by marceloverdijk** [comment]
Do you maybe have an ETA for a next version of the lib? Especially this change is very needed in my project.

**Comment by jasminb** [comment]
@marceloverdijk should be today/tommorow

**Comment by marceloverdijk** [comment]
@jasminb did you find any time to publish a new release?

**Comment by jasminb** [comment]
@marceloverdijk Just did it, https://github.com/jasminb/jsonapi-converter/releases/tag/0.8.1

**Pull request merged**
